export type AgentExecutionError =
	| 'agent-execution-agent-not-found'
	| 'agent-execution-secret-not-found'
	| 'agent-execution-provider-unsupported'
	| 'agent-execution-api-key-required'
	| 'agent-execution-prompt-required'
	| 'agent-execution-model-required'
	| 'agent-execution-request-invalid'
	| 'agent-execution-authentication-failed'
	| 'agent-execution-rate-limited'
	| 'agent-execution-provider-rejected'
	| 'agent-execution-provider-timeout'
	| 'agent-execution-provider-unavailable'
	| 'agent-execution-response-empty'
	| 'agent-execution-response-invalid'
	| 'agent-execution-unavailable';
