// @generated by scripts/sync-ssealed-scaffold.mjs --write. Do not edit by hand.

export const SSEALED_SCAFFOLD_SCOPES = [
	"backend",
	"frontend",
	"fullstack",
	"general",
	"mobile",
	"infra",
	"data"
] as const;

export const SSEALED_SCAFFOLD_PROFILES = [
	"generic",
	"cli-tool",
	"api-service",
	"desktop-app",
	"library",
	"web-app",
	"mobile-app",
	"sdk",
	"worker-service",
	"infra-module",
	"data-pipeline",
	"github-action",
	"browser-extension",
	"plugin",
	"docs-site",
	"monorepo"
] as const;
