// @generated by scripts/sync-ssealed-scaffold.mjs --write. Do not edit by hand.

pub const SSEALED_SCAFFOLD_ARCHIVE_SCHEMA_VERSION: &str = "workduck.ssealed-scaffold-archive/v1";
pub const SSEALED_SCAFFOLD_TOOL_VERSION: &str = "0.6.11";
pub const SSEALED_SCAFFOLD_ARCHIVE_SHA256: &str = "f430496e8f3225ecfeed6a921e974b821535bd90b53a91102c730e2070e1ce62";
pub const SSEALED_SCAFFOLD_ARCHIVE_JSON: &str =
	include_str!("../resources/ssealed-scaffolds-v1.json");
