// @generated by scripts/sync-ssealed-scaffold.mjs --write. Do not edit by hand.

pub const SSEALED_SCAFFOLD_ARCHIVE_SCHEMA_VERSION: &str = "workduck.ssealed-scaffold-archive/v1";
pub const SSEALED_SCAFFOLD_TOOL_VERSION: &str = "0.7.0";
pub const SSEALED_SCAFFOLD_ARCHIVE_SHA256: &str = "e88cfb2115192bc69231c3fabe5810520248657c0962145c9d838403cfeffab0";
pub const SSEALED_SCAFFOLD_ARCHIVE_JSON: &str =
	include_str!("../resources/ssealed-scaffolds-v1.json");
