// @generated by scripts/sync-ssealed-scaffold.mjs --write. Do not edit by hand.

pub const SSEALED_SCAFFOLD_ARCHIVE_SCHEMA_VERSION: &str = "workduck.ssealed-scaffold-archive/v1";
pub const SSEALED_SCAFFOLD_TOOL_VERSION: &str = "0.7.79";
pub const SSEALED_SCAFFOLD_ARCHIVE_SHA256: &str = "02f2aecf3672289a09c00c7c1175093449d525684dafc6524df9e8d8acd39108";
pub const SSEALED_SCAFFOLD_ARCHIVE_JSON: &str =
	include_str!("../resources/ssealed-scaffolds-v1.json");
